services:

  grafana-app:
    image: docker.io/nfrastack/grafana:latest
    container_name: grafana-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana-app.rule=Host(`grafana.example.com`)
      - traefik.http.services.grafana-app.loadbalancer.server.port=3000
    volumes:
      - ./config:/config
      - ./data:/data
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
    networks:
      - proxy
      - services
    restart: always

  grafana-db:
    image: docker.io/nfrastack/mariadb:11.8
    container_name: grafana-db
    volumes:
      - ./db:/data
      - ./logs/mariadb:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=grafana-db

      - ROOT_PASS=root_password
      - DB_NAME=grafana
      - DB_USER=grafana
      - DB_PASS=user_password
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
